### ISSUE TITLE
Error: Port is opening (Linux and Windows)

### ISSUE THREAD

**Issue by Kaplas85** [node-escpos/driver#13]
Hi! I'm trying to use a thermal printer Dascom DT-230 with the serialport adapter. Now the printer is connected to my PC using usb but the pc detects that as a serial port

In Windows as `COM4`
In Linux as `/dev/ttyACM0`

In both cases that return `Error: Port is opening`
![image](https://user-images.githubusercontent.com/53917815/198046337-2757ce1a-39ac-4c8a-b9de-0ce2c4bcdf3b.png)

It's the code that I was testing

``` javascript
import { Printer } from "@node-escpos/core";
import Serial from "@node-escpos/serialport-adapter";

const device = new Serial("/dev/ttyACM0", { // In Windows I was put "COM4"
  baudRate: 115200,
  stopBit: 1,
});

const options = {
  encoding: "utf-8",
};

const printer = new Printer(device, options);

device.open((error) => {
  if (error) {
    console.error(error);
    return;
  }

  let printer = new Printer(device, {});

  printer
    .font("a")
    .align("ct")
    .style("bu")
    .size(1, 1)
    .text("The quick brown fox jumps over the lazy dog");

  printer.cut().close();
});

```

Someone can help me with that? I have been trying different packages to use escpos printers for months and I have not found any that give me results

**Comment by dohooo** [comment]
This problem is related to this [issue](https://github.com/serialport/node-serialport/issues/752).

**Comment by Kaplas85** [comment]
I was update the serial port package and that solve the bug but still the printer don't print any. 

I also don't get any output in the console

**Comment by dohooo** [comment]
> I was update the serial port package and that solve the bug but still the printer don't print any.
> 
> I also don't get any output in the console

Okay, let me check again.

**Comment by Kaplas85** [comment]
Hello! I will close this issue because the problem was not the package, was the printer.

I was try with a new printer and works fine.
