### ISSUE TITLE
Cannot change Barcode spacing between lines with Barcode Options

### ISSUE THREAD

**Issue by YovanggaAnandhika** [node-escpos/driver#19]
Unlike @escpos Parent Repository. i cannot set witdh and height barcode in paper 80 mm
if is a long number the barcode is long.

I hope the barcode scales left and right if the data number is short;

````typescript
printer.text('The quick brown fox jumps over the lazy dog')
        .barcode(65656556565,"CODE39", {
                    width : 50,
                    height : 50,
        })
         .cut()
         .close()
````

Spacing between Barcode Rows functions so that the barcode can be seen clearly when scanned

**Comment by dohooo** [comment]
Can you take a photo for me?

**Comment by YovanggaAnandhika** [comment]
yes sure buddy.

i am use a same code style, same printer device.
and use VSC Thermall Print TM-801

code like this :
````typescript
printer
        .font('a')
        .align('ct')
        .size(0,0)
        .text("FROM LIBRARY escpos")
        .barcode('12345678388382', 'CODE39', {
            width : 1,
            height : 90
        })
        .cut()
        .close();
````

output like this 

![IMG_20221125_004320](https://user-images.githubusercontent.com/15067521/203834144-b230750a-2747-4063-b0d1-15d00d775c06.jpg)

**Comment by YovanggaAnandhika** [comment]
i am test console log barcode options is Like This

![image](https://user-images.githubusercontent.com/15067521/203839231-0067bc7b-9090-4923-9563-7b4703944d02.png)

and result console.log is 
![image](https://user-images.githubusercontent.com/15067521/203839348-5602fae1-0832-4544-be80-f3701791b882.png)

height is undefined !!!

**Comment by YovanggaAnandhika** [comment]
![image](https://user-images.githubusercontent.com/15067521/203839541-2f51a8a8-0064-4de3-b646-ee8fbd2b3876.png)

i Am Found The Solution. Finally

**Comment by dohooo** [comment]
> this is awesome project buddy. please revision code i am so need for my project. thanksfull. release and NPM

Awesome work! But I'm busy recently.So can you give a PR for this? I'll merge it and publishing.

**Comment by dohooo** [comment]
It's 1:35 AM in my place. I'm going to bed. 😵‍💫😵‍💫😵‍💫

**Comment by YovanggaAnandhika** [comment]
Solved to Pull Request on [this pull request](https://github.com/node-escpos/driver/pull/25#issue-1463676036)
