### ISSUE TITLE
Typesetting problems when printing？

### ISSUE THREAD

**Issue by fecherwu** [node-escpos/driver#29]
你好，有看到新node-escpos的更新，對於排版上我遇到了一些麻煩，想請問是否能做到以下的排版設計？

![help_d_4_01](https://user-images.githubusercontent.com/72546633/205221859-3b9ab247-e292-42f7-bec4-9b212d8e8ade.gif)
請問是否能讓兩QRcode 對齊列印？

**Comment by dohooo** [comment]
目前可能不行，我正在开发一个新的打印模式，标签打印的内容将完全由 HTML+CSS 来进行定制，所以理论上我们能实现任何的打印样式。流程大概如下：
1. render dom
2. capture dom
3. printing

不过目前我无法花更多精力在开源项目上，所以进度会很缓慢，如果能获得任何支持我会非常感谢。 
---
Currently is not. I'm working on a new workflow that prints the receipt. HTML+CSS will customize the content. Theoretically, we can print anything that we want. The workflow is like this:
1. render dom
2. capture dom
3. printing

I'm working in my full-time occupation busily. So the progress is slow, And any sponsorship will encourage me to work  more actively in the open-source community.
