### ISSUE TITLE
[FEATURE REQUEST] Implement bluetooth-adapter.

### ISSUE THREAD

**Issue by dohooo** [node-escpos/driver#34]
Currently, I don't have any Bluetooth printer to test, so I can't implement this adapter. If you have a Bluetooth printer and want to help, welcome PR.

> BTW, maybe [`nouble`](https://github.com/noble/noble) is a good choice for this part.

**Comment by lucasfernog** [comment]
I don't know exacly what I need to do for the adapter, but I got it to work using noble:

```javascript
const noble = require('@abandonware/noble')({ extended: false });

noble.on('stateChange', async (state) => {
  if (state === 'poweredOn') {
    await noble.startScanningAsync(['18f0'], false);
  }
});

noble.on('discover', async (peripheral) => {
  await peripheral.connectAsync();
  const { characteristics } = await peripheral.discoverSomeServicesAndCharacteristicsAsync(['18f0'], ['2af1']);
  const characteristic = characteristics[0];
  await characteristic.writeAsync(printer.buffer.flush(), false);
});
```

**Comment by dohooo** [comment]
Awesome work! Then you need to implement Adapter class from @escpos-node/adapter and make the types compatible. You can refer to this [adapter](https://github.com/node-escpos/driver/blob/main/packages/serialport-adapter/src/index.ts).
